"""empty message

Revision ID: 199a57a48638
Revises: daf6adebdc93
Create Date: 2020-05-06 02:27:35.615256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '199a57a48638'
down_revision = 'daf6adebdc93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_data', sa.Column('wordCount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_data', 'wordCount')
    # ### end Alembic commands ###
