"""empty message

Revision ID: c2127e2646d7
Revises: 199a57a48638
Create Date: 2020-05-06 02:55:04.660766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2127e2646d7'
down_revision = '199a57a48638'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('lastLogin', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_lastLogin'), 'user', ['lastLogin'], unique=False)
    op.add_column('user_data', sa.Column('correctSentences', sa.Integer(), nullable=True))
    op.add_column('user_data', sa.Column('loginStreak', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_data', 'loginStreak')
    op.drop_column('user_data', 'correctSentences')
    op.drop_index(op.f('ix_user_lastLogin'), table_name='user')
    op.drop_column('user', 'lastLogin')
    # ### end Alembic commands ###
